[package]
name = "matchit-serde"
version = "0.1.0"
edition = "2024"

[dependencies]
matchit = "0.8"
serde = { version = "1.0", features = ["serde_derive"] }
derive_more = { version = "2.0", features = ["display"] }
thiserror = "2.0"
